from typing import List, Optional, Protocol, Dict, Any

class TodoRepo(Protocol):
    async def create(self, data: Dict[str, Any]) -> dict: ...
    async def get(self, todo_id: int) -> Optional[dict]: ...
    async def list(self, *, status: Optional[str]=None, priority: Optional[int]=None,
                   q: Optional[str]=None, overdue: Optional[bool]=None,
                   limit: int = 50, offset: int = 0) -> List[dict]: ...
    async def update(self, todo_id: int, changes: Dict[str, Any]) -> Optional[dict]: ...
    async def delete(self, todo_id: int) -> bool: ...
    async def toggle(self, todo_id: int) -> Optional[dict]: ...
    async def bulk_create(self, items: List[Dict[str, Any]]) -> List[dict]: ...
