from typing import List, Optional, Protocol

class TodoRepo(Protocol):
    async def create(self, title: str) -> dict: ...
    async def get(self, todo_id: int) -> Optional[dict]: ...
    async def list(self) -> List[dict]: ...
    async def update(self, todo_id: int, title: str) -> Optional[dict]: ...
    async def delete(self, todo_id: int) -> bool: ...
